// Mocks generated by Mockito 5.4.0 from annotations
// in tatsujin_guild/test/repositories/post_repository/post_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsujin_guild/models/post/post.dart' as _i4;
import 'package:tatsujin_guild/repositories/post_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PostRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepositoryImpl extends _i1.Mock
    implements _i2.PostRepositoryImpl {
  @override
  _i3.Future<List<_i4.Post>> getRankingPosts() => (super.noSuchMethod(
        Invocation.method(
          #getRankingPosts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
      ) as _i3.Future<List<_i4.Post>>);
  @override
  _i3.Future<List<_i4.Post>> getTimeLinePosts() => (super.noSuchMethod(
        Invocation.method(
          #getTimeLinePosts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
      ) as _i3.Future<List<_i4.Post>>);
  @override
  _i3.Future<List<_i4.Post>> getMyPosts() => (super.noSuchMethod(
        Invocation.method(
          #getMyPosts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
      ) as _i3.Future<List<_i4.Post>>);
  @override
  _i3.Future<List<_i4.Post>> getFavoritePosts() => (super.noSuchMethod(
        Invocation.method(
          #getFavoritePosts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
      ) as _i3.Future<List<_i4.Post>>);
  @override
  _i3.Future<bool> postTimeLinePost({required _i4.Post? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #postTimeLinePost,
          [],
          {#post: post},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteMyPost({required _i4.Post? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMyPost,
          [],
          {#post: post},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteFavoritePost({required _i4.Post? post}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFavoritePost,
          [],
          {#post: post},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
